export type CreateLoanProductsRequest = {
    id: string | number,
    dateCreated: string | number,
    dateModified: string | number,
    createdBy: string,
    createdByIp: string,
    modifiedBy: string,
    modifiedByIp: string,
    isDeleted: boolean,
    version: string | number,
    status: string,
    isThirdPartyLoanProduct: string,
    holdFundForSecurityDeposit: string,
    interestID: string | number,
    apr: string | number,
    useDefaultAPR: string,
    loanCycle: string | number,
    moratarium: string | number,
    loanPenaltyID: string | number,
    loanSizeRange: string | number,
    loanRangeFrom: string | number,
    loanRangeTo: string | number,
    flatAmount: string | number,
    principalRepaymentType: string | number,
    principalPaymentFrequency: string | number,
    interestRepaymentType: string | number,
    interestPaymentFrequency: string | number,
    interestAccrualMode: string | number,
    applyPenalty: string,
    penaltyPercentage: string | number,
    penaltyFlat: string | number,
    penaltyGracePeriod: string | number,
    applyLoanFees: string,
    nonPerformingLoanInterestAccrual: string | number,
    period: string | number,
    loanPercentage: string | number,
    minSavingBalance: string | number,
    principalOverdueAccountID: string | number,
    feesOutstandingAccountID: string | number,
    feesInSuspenseAccountID: string | number,
    overdraftInterestReceivableAccountID: string | number,
    overdraftInterestOverdueAccountID: string | number,
    overdraftInterestInSuspenseAccountID: string | number,
    feesIncomeAccountID: string | number,
    penaltyIncomeAccountID: string | number,
    penaltyOutstandingAccountID: string | number,
    penaltyInSuspenseAccountID: string | number,
    specificLoanAndLeaseLossProvis: string | number,
    generalLoanAndLeaseLossProvis: string | number,
    interestIncomeAccountID: string | number,
    defaultingLoanInterest: string | number,
}
export const createLoanProductsRequestInit: CreateLoanProductsRequest = {
    id: 0,
    dateCreated: "",
    dateModified: "",
    createdBy: "",
    createdByIp: "",
    modifiedBy: "",
    modifiedByIp: "1",
    isDeleted: true,
    version: 1,
    status: "A",
    isThirdPartyLoanProduct: "false",
    holdFundForSecurityDeposit: "false",
    interestID: "",
    apr: "",
    useDefaultAPR: "false",
    loanCycle: "",
    moratarium: "",
    loanPenaltyID: "",
    loanSizeRange: "",
    loanRangeFrom: "",
    loanRangeTo: "",
    flatAmount: "",
    principalRepaymentType: "",
    principalPaymentFrequency: "",
    interestRepaymentType: "",
    interestPaymentFrequency: "",
    interestAccrualMode: "",
    applyPenalty: "false",
    penaltyPercentage: "",
    penaltyFlat: "",
    penaltyGracePeriod: "",
    applyLoanFees: "false",
    nonPerformingLoanInterestAccrual: "",
    period: "",
    loanPercentage: "",
    minSavingBalance: "",
    principalOverdueAccountID: "",
    feesOutstandingAccountID: "",
    feesInSuspenseAccountID: "",
    overdraftInterestReceivableAccountID: "",
    overdraftInterestOverdueAccountID: "",
    overdraftInterestInSuspenseAccountID: "",
    feesIncomeAccountID: "",
    penaltyIncomeAccountID: "",
    penaltyOutstandingAccountID: "",
    penaltyInSuspenseAccountID: "",
    specificLoanAndLeaseLossProvis: "",
    generalLoanAndLeaseLossProvis: "",
    interestIncomeAccountID: "",
    defaultingLoanInterest: 0
}
