import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Providers} from "@/components/custom/reduxProvider";
import GlobalModal from "@/components/ui/modal/GlobalModal";
import BaseToastContainer from "@/components/ui/toast/BaseToastContainer";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });
// const inter = Inter({subsets: ['latin']})
const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Providers>
            <GlobalModal/>
            <BaseToastContainer/>
            {children}
        </Providers>
        </body>
        </html>
    );
}
