export type SearchLetterOfCreditRequest = {
    letterOfCreditAdditionalConditions?: string,
    letterOfCreditAdviseDirect?: string,
    letterOfCreditApplicableRules?: string,
    letterOfCreditLetterOfCredit?: string,
    letterOfCreditLetterOfCreditNameandaddress?: string,
    letterOfCreditLetterOfCreditReference?: string,
    letterOfCreditApplicationDate?: string,
    letterOfCreditAutomaticallyCreateFollowOnEvent?: string,
    letterOfCreditAvailableWith?: string,
    letterOfCreditBidDate?: string,
    letterOfCreditBidNumber?: string,
    letterOfCreditConfirmation?: string,
    letterOfCreditCreatedAt?: string,
    letterOfCreditDocumentsRequired?: string,
    letterOfCreditDocumentsToBeSentBy?: string,
    letterOfCreditDomesticExpiry?: string,
    letterOfCreditExpiryDate?: string,
    letterOfCreditExpiryPlace?: string,
    letterOfCreditFinalWording?: string,
    letterOfCreditForPercentageOfInvoice?: string,
    letterOfCreditFreight?: string,
    letterOfCreditFrom?: string,
    letterOfCreditGoodsCode?: string,
    letterOfCreditGoodsDescription?: string,
    letterOfCreditId?: number,
    letterOfCreditIncoterms?: string,
    letterOfCreditInsuranceForBuyer?: string,
    letterOfCreditIrrevocable?: string,
    letterOfCreditIssueBy?: string,
    letterOfCreditIssueDate?: string,
    letterOfCreditNoOfPackagesDeliveryItems?: string,
    letterOfCreditOperative?: string,
    letterOfCreditPartialShipments?: string,
    letterOfCreditPlaceOfDischargeDestination?: string,
    letterOfCreditPlaceOfLoadingDeparture?: string,
    letterOfCreditPreadviceDate?: string,
    letterOfCreditPresentationPeriodNarrative?: string,
    letterOfCreditPresentationPeriodNoOfDays?: string,
    letterOfCreditProductType?: string,
    letterOfCreditProvisional?: string,
    letterOfCreditRevolving?: string,
    letterOfCreditSectorialPurpose?: string,
    letterOfCreditShipmentDate?: string,
    letterOfCreditShipmentPeriod?: string,
    letterOfCreditSpecialPaymentConditionsForBeneficiary?: string,
    letterOfCreditSpecialPaymentConditionsForReceivingBank?: string,
    letterOfCreditStatus?: string,
    letterOfCreditTo?: string,
    letterOfCreditTransferable?: string,
    letterOfCreditTranshipments?: string,
    letterOfCreditUpdatedAt?: string,
    locReference?: string,
    search?: string;
    sortBy?: string;
    sortDir?: string;
    pageNumber?: number;
    pageSize?: number;
}

export const searchLetterOfCreditRequestInit: SearchLetterOfCreditRequest = {
    search: "",
    sortBy: "letterOfCreditId",
    sortDir: "DESC",
    pageNumber: 1,
    pageSize: 10,


}
